title: bakdogyun
email: bakdogyun@gmail.com
description: A Blog by Dogyun Bak
author: Dogyun Bak
baseurl: "/"
url: "https://bakdogyun.github.io"

# Social Profiles
twitter_username:
github_username: bakdogyun
facebook_username:
instagram_username: bakdogyun
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
